disabled_rules:
- trailing_whitespace
- line_length
- large_tuple
- force_cast
- cyclomatic_complexity
- type_body_length
- file_length
- todo

opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_name:
    max_length:
        warning: 50
        error: 60
    min_length:
        warning: 3
reporter: "xcode"
